account_class: account_class.cc
	g++ account_class.cc -o account_class

random: random.cc
	g++ random.cc -o random

montecarlo: montecarlo.cc
	g++ montecarlo.cc -o montecarlo

incrementer: incrementer.cc
	g++ incrementer.cc -o incrementer

test_rational: test_rational.cc Rational.cc Rational.hh
	g++ test_rational.cc -o test_rational
