account_class: account_class.cc
	g++ account_class.cc -o account_class

class02: class02.cc
	g++ class02.cc -o class02

random: random.cc
	g++ random.cc -o random

montecarlo: montecarlo.cc
	g++ montecarlo.cc -o montecarlo

incrementer: incrementer.cc
	g++ incrementer.cc -o incrementer

test_rational: test_rational.cc Rational.cc Rational.hh
	g++ test_rational.cc -o test_rational

class03: class03.cc Rational.cc Rational.hh
	g++ class03.cc -o class03

class04: class04.cc Rational.cc Rational.hh
	g++ class04.cc -o class04
