test_stl: test_stl.cc
	g++ -o test_stl test_stl.cc
test_list: test_list.cc
	g++ -o test_list test_list.cc
test_dllist: test_dllist.cc
	g++ -o test_dllist test_dllist.cc
test_arr: test_arr.cc
	g++ -o test_arr test_arr.cc
test_stack: test_stack.cc
	g++ -o test_stack test_stack.cc
test_pointer: test_pointer.cc
	g++ -o test_pointer test_pointer.cc
list02: list02.cc
	g++ -o list02 list02.cc
list03: list03.cc
	g++ -o list03 list03.cc
list04: list04.cc
	g++ -o list04 list04.cc
test_queue: test_queue.cc queue.hh
	g++ -o test_queue test_queue.cc
test_dequeue: test_dequeue.cc dequeue.hh
	g++ -o test_dequeue test_dequeue.cc
test_mpq: test_mpq.cc min_priority_queue.hh min_priority_queue.cc
	g++ -o test_mpq test_mpq.cc
test_set: test_set.cc set.hh set.cc dl_list.cc dl_list.hh
	g++ -o test_set test_set.cc