test_stl: test_stl.cc
	g++ -o test_stl test_stl.cc
test_list: test_list.cc
	g++ -o test_list test_list.cc
test_dllist: test_dllist.cc
	g++ -o test_dllist test_dllist.cc
test_arr: test_arr.cc
	g++ -o test_arr test_arr.cc
