quadrat: quadrat.cc
	g++ -o quadrat quadrat.cc

absolut: absolut.cc
	g++ -o absolut absolut.cc

alles_funktional: alles_funktional.cc
	g++ -o alles_funktional alles_funktional.cc

facf: facf.cc
	g++ -o facf facf.cc

fakit: fakit.cc
	g++ -o fakit fakit.cc

fakit02: fakit02.cc
	g++ -o fakit02 fakit02.cc

fibrek: fibrek.cc
	g++ -o fibrek fibrek.cc

fibit: fibit.cc
	g++ -o fibit fibit.cc