enum: enum.cc
	g++ enum.cc -o enum

print_ascii: print_ascii.cc
	g++ print_ascii.cc -o print_ascii

print_string: print_string.cc
	g++ print_string.cc -o print_string

rational: rational.cc
	g++ rational.cc -o rational

complex: complex.cc
	g++ complex.cc -o complex

stack: stack.cc
	g++ stack.cc -o stack