circ: circ.cc 
	g++ -o circ circ.cc

fibit01: fibit01.cc 
	g++ -o fibit01 fibit01.cc

absolut: absolut.cc 
	g++ -o absolut absolut.cc

fak: fak.cc 
	g++ -o fak fak.cc

fakfor: fakfor.cc 
	g++ -o fakfor fakfor.cc

vile: vile.cc 
	g++ -o vile vile.cc

fibfor: fibfor.cc 
	g++ -o fibfor fibfor.cc

squareroot: squareroot.cc 
	g++ -o squareroot squareroot.cc

fakgo: fakgo.cc 
	g++ -o fakgo fakgo.cc