templates: templates.cc
	g++ -o templates templates.cc
func_templates: func_templates.cc
	g++ -o func_templates func_templates.cc
class_templates: class_templates.cc
	g++ -o class_templates class_templates.cc