arr_test: arr_test.cc arr.hh
	g++ -o arr_test arr_test.cc
test_polynomial: test_polynomial.cc
	g++ -o test_polynomial test_polynomial.cc 
test_arr: test_arr.cc
	g++ -o test_arr test_arr.cc
test_subclass: test_subclass.cc
	g++ -o test_subclass test_subclass.cc
test_test_inheritence: test_test_inheritence.cc
	g++ -o test_test_inheritence test_test_inheritence.cc