pointer01: pointer01.cc
	g++ pointer01.cc -o pointer01

accounts: accounts.cc
	g++ accounts.cc -o accounts

structure_pointers: structure_pointers.cc
	g++ structure_pointers.cc -o structure_pointers

alphabet: alphabet.cc
	g++ alphabet.cc -o alphabet

dynamic: dynamic.cc
	g++ dynamic.cc -o dynamic

set: set.cc
	g++ set.cc -o set