pointer01: pointer01.cc
	g++ pointer01.cc -o pointer01

pointer02: pointer02.cc
	g++ pointer02.cc -o pointer02

accounts: accounts.cc
	g++ accounts.cc -o accounts

accounts02: accounts02.cc
	g++ accounts02.cc -o accounts02

structure_pointers: structure_pointers.cc
	g++ structure_pointers.cc -o structure_pointers

alphabet: alphabet.cc
	g++ alphabet.cc -o alphabet

dynamic: dynamic.cc
	g++ dynamic.cc -o dynamic

set: set.cc
	g++ set.cc -o set

struct02: struct02.cc
	g++ struct02.cc -o struct02

pointer03: pointer03.cc
	g++ pointer03.cc -o pointer03

accounts03: accounts03.cc
	g++ accounts03.cc -o accounts03

struct03: struct03.cc
	g++ struct03.cc -o struct03

dynamic02: dynamic02.cc
	g++ dynamic02.cc -o dynamic02

list03: list03.cc
	g++ list03.cc -o list03

set03: set03.cc
	g++ set03.cc -o set03