pointer01: pointer01.cc
	g++ pointer01.cc -o pointer01

pointer02: pointer02.cc
	g++ pointer02.cc -o pointer02

accounts: accounts.cc
	g++ accounts.cc -o accounts

accounts02: accounts02.cc
	g++ accounts02.cc -o accounts02

structure_pointers: structure_pointers.cc
	g++ structure_pointers.cc -o structure_pointers

alphabet: alphabet.cc
	g++ alphabet.cc -o alphabet

dynamic: dynamic.cc
	g++ dynamic.cc -o dynamic

set: set.cc
	g++ set.cc -o set

struct02: struct02.cc
	g++ struct02.cc -o struct02