float_arr_test: float_arr_test.cc
	g++ -o float_arr_test float_arr_test.cc

namespaces: namespaces.cc
	g++ -o namespaces namespaces.cc

iostream_test: iostream_test.cc
	g++ -o iostream_test iostream_test.cc

float_arr03: float_arr03.cc
	g++ -o float_arr03 float_arr03.cc